//POST http://localhost:4000/app/signup
//Content-Type: application/json

//{
  //  "fullName":"Joseph",
  //  "username":"joey",
  //  "email":"joe@gmail.com",
  //  "password":"josejosey"
//}


//POST http://localhost:4000/api/auth/register
//Content-Type: application/json

//{

//     "username":"remi" ,
//     "email":"remi.carvalot5@gmail.com" ,
//     "password":"azerty"
     
     
//}*/

POST http://localhost:8800/api/posts/
Content-Type: application/json

{

    "userId":"6280f945f2dd5f105ac9258a" ,
     "desc":"remi.carvalot5@gmail.com" ,
     "img":"post/1.jpeg"
     
     
}

